CompetentumWebApp/Controllers/AdminLteController.cs
using CompetentumWebApp.Models;
using Flurl.Http;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.IO;
using System.Security.Cryptography.X509Certificates;
using System.Net.Security;
using Newtonsoft.Json;
using System.Web.UI.WebControls;
using System.Web.UI;
using OfficeOpenXml;
using OfficeOpenXml.Style;

namespace AdminLteMvc.Controllers
{
    /// <summary>
    /// This is an example controller using the AdminLTE NuGet package's CSHTML templates, CSS, and JavaScript
    /// You can delete these, or use them as handy references when building your own applications
    /// </summary>
    public class AdminLteController : Controller
    {
        /// <summary>
        /// The home page of the AdminLTE demo dashboard, recreated in this new system
        /// </summary>
        /// <returns></returns>
        ResumeContext db = new ResumeContext();
        public ActionResult Index()
        {
            var vacancies = db.Vacancies
                .Include(v => v.VacancyState);
            return View(vacancies.ToList());
        }

        [HttpGet]
        public ActionResult VacancyCreate()//создание новой вакансии
        {
            SelectList Vacancystates = new SelectList(db.VacancyStates, "Id", "VacancyStateName");
            ViewBag.VacancyStates = Vacancystates;

            return View();
        }

        [HttpPost]
        public ActionResult VacancyCreate(Vacancy newvacancy)//получаем введенные данные по вакансии
        {
            //Добавляем вакансию в таблицу
            db.Vacancies.Add(newvacancy);
            db.SaveChanges();
            // перенаправляем на главную страницу
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult VacancyEdit(int? id)//получаем id редактируемой вакансии
        {
            if (id == null)
            {
                return HttpNotFound();
            }
            // Находим в бд вакансию
            Vacancy newvacancy = db.Vacancies.Find(id);
            if (newvacancy != null)
            {
                SelectList Vacancystates = new SelectList(db.VacancyStates, "Id", "VacancyStateName");
                ViewBag.VacancyStates = Vacancystates;

                return View(newvacancy);
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult VacancyEdit(Vacancy newvacancy)//получаем введенные пользователем данные через модель Vacancy
        {
            db.Entry(newvacancy).State = EntityState.Modified;//устанавливаем для этой модели статус Modified
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult VacancyDetails(int? id)
        {
            Vacancy Vacancydetails = db.Vacancies.Find(id);

            if (id == null)
            {
                return HttpNotFound();
            }
            
            //ViewBag.Vacancys = db.Vacancys.ToList();

            return View(Vacancydetails);
        }

        [HttpGet]
        public ActionResult VacancyDelete(int? id)//получаем id удаляемого резюме
        {
            if (id == null)
            {
                return HttpNotFound();
            }
            // Находим в бд вакансию
            Vacancy newvacancy = db.Vacancies.Find(id);
            if (newvacancy != null)
            {
                db.Vacancies.Remove(newvacancy);
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        /// <summary>
        /// //////////////////////////////////////////////////////////////          РЕЗЮМЕ          //////////////////////////////////////////////////////////////
        /// </summary>
        /// <returns></returns>

        public ActionResult ResumeView()
        {
            var resumes = db.Resumes
                .Include(p => p.State)
                .Include(p => p.Currency)
                .Include(p => p.Schedule)
                .Include(p => p.EmploymentName)
                .Include(p => p.educationalLevel)
                .Include(p => p.languageLevel)
                .Include(p => p.language)
                .Include(p => p.Source)
                .Include(p => p.Gender);
            return View(resumes.ToList());
        }

        [HttpGet]
        public ActionResult Create()//создание нового резюме
        {
            SelectList states = new SelectList(db.States, "Id", "StateName");
            ViewBag.States = states;

            SelectList currencies = new SelectList(db.Currencies, "Id", "CurrencyName");
            ViewBag.Currencies = currencies;

            SelectList schedules = new SelectList(db.Schedules, "Id", "ScheduleName");
            ViewBag.Schedules = schedules;

            SelectList empoymentnames = new SelectList(db.EmploymentNames, "Id", "Employement_Name");
            ViewBag.EmploymentNames = empoymentnames;

            SelectList educationallevels = new SelectList(db.educationalLevels, "Id", "name");
            ViewBag.educationalLevels = educationallevels;

            SelectList languagelevels = new SelectList(db.languageLevels, "Id", "Level_name");
            ViewBag.languageLevels = languagelevels;

            SelectList languages = new SelectList(db.languages, "Id", "list_name");
            ViewBag.languages = languages;

            SelectList sources = new SelectList(db.Sources, "Id", "SourceName");
            ViewBag.Sources = sources;

            SelectList genders = new SelectList(db.Genders, "Id", "GenderName");
            ViewBag.Genders = genders;

            return View();
        }

        [HttpPost]
        public ActionResult Create(Resume user)//получаем введенные данные
        {
            //Добавляем пользователя в таблицу
            db.Resumes.Add(user);
            db.SaveChanges();
            // перенаправляем на страницу с БД Резюме
            return RedirectToAction("ResumeView");
        }

        [HttpGet]
        public ActionResult Edit(int? id)//получаем id редактируемого резюме
        {
            if (id == null)
            {
                return HttpNotFound();
            }
            // Находим в бд резюме
            Resume user = db.Resumes.Find(id);
            if (user != null)
            {
                SelectList states = new SelectList(db.States, "Id", "StateName");
                ViewBag.States = states;

                SelectList currencies = new SelectList(db.Currencies, "Id", "CurrencyName");
                ViewBag.Currencies = currencies;

                SelectList schedules = new SelectList(db.Schedules, "Id", "ScheduleName");
                ViewBag.Schedules = schedules;

                SelectList empoymentnames = new SelectList(db.EmploymentNames, "Id", "Employement_Name");
                ViewBag.EmploymentNames = empoymentnames;

                SelectList educationallevels = new SelectList(db.educationalLevels, "Id", "name");
                ViewBag.educationalLevels = educationallevels;

                SelectList languagelevels = new SelectList(db.languageLevels, "Id", "Level_name");
                ViewBag.languageLevels = languagelevels;

                SelectList languages = new SelectList(db.languages, "Id", "list_name");
                ViewBag.languages = languages;

                SelectList sources = new SelectList(db.Sources, "Id", "SourceName");
                ViewBag.Sources = sources;

                SelectList genders = new SelectList(db.Genders, "Id", "GenderName");
                ViewBag.Genders = genders;

                return View(user);
            }
            return RedirectToAction("ResumeView");
        }

        [HttpPost]
        public ActionResult Edit(Resume user)//получаем введенные пользователем данные через модель Resume
        {
            db.Entry(user).State = EntityState.Modified;//устанавливаем для этой модели статус Modified
            db.SaveChanges();
            return RedirectToAction("ResumeView");
        }

        [HttpGet]
        public ActionResult Delete(int? id)//получаем id удаляемого резюме
        {
            if (id == null)
            {
                return HttpNotFound();
            }
            // Находим в бд резюме
            Resume user = db.Resumes.Find(id);
            if (user != null)
            {
                db.Resumes.Remove(user);
                db.SaveChanges();
            }
            return RedirectToAction("ResumeView");
        }

        public ActionResult Details(int? id)
        {

            Resume details = db.Resumes
            .Include(p => p.State)
            .Include(p => p.Currency)
            .Include(p => p.Schedule)
            .Include(p => p.EmploymentName)
            .Include(p => p.educationalLevel)
            .Include(p => p.languageLevel)
            .Include(p => p.language)
            .Include(p => p.Source)
            .Include(p => p.Gender).FirstOrDefault(p => p.Id == id);

            if (id == null)
            {
                return HttpNotFound();
            }

            return View(details);
        }

        public ActionResult ExportToExcel()
        {
            var gv = new GridView();
            gv.DataSource = (from e in db.Vacancies
                             join d in db.VacancyStates on e.VacancyStateId equals d.Id
                             select new ExcelModel
                             {
                                 ID = e.Id,
                                 VacName = e.VacancyName,
                                 VacState = d.VacancyStateName,
                                 VacCreationDate = e.VacancyCreationDate,
                                 VacInititator = e.VacancyInitiator,
                                 VacRegion = e.VacancyRegion,

CompetentumWebApp/Views/Shared/_AdminLteBreadcrumb.cshtml
@* 
 This breadcrumb partial is meant to be dropped into the top of the main content page
    and uses the AdminLte.Breadcrumb class to dynamically build the breadcrumb per page
*@

@if (ViewBag.Breadcrumb != null)
{
    <ol class="breadcrumb">
        @foreach (Crumb crumb in ViewBag.Breadcrumb)
        {
            <li>
                @if (crumb.HasLink)
                {
                    <a href="@crumb.Link">
                        @if (crumb.HasIcon)
                        {
                            <i class="fa @crumb.Icon"></i>
                        }

                        <span>@crumb.Text</span>
                    </a>
                }
                else
                {
                    if (crumb.HasIcon)
                    {
                        <i class="fa @crumb.Icon"></i>
                    }

                    <span>@crumb.Text</span>
                }
            </li>
        }
    </ol>
}

CompetentumWebApp/Views/Shared/_AdminLteLayout.cshtml
@* 
 This is the main dashboard layout that creates the AdminLTE look and feel
    It includes all of the relevant CSS and Js in this project and across CDNs around the web for optimal load times
    TODO: Use this layout in your views by either setting the "Layout" property 
    or changing your  _ViewStart.cshtml to use this layout
 *@

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @*TODO: Change App name*@
    <title>@ViewBag.Title - My ASP.NET Application</title>

    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    @*Source Sans Pro from Google Fonts*@
    <link href="//fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic" rel="stylesheet" />
    @*Bundle CSS, assuming includes Bootstrap CSS *@
    @Styles.Render("~/Content/css")
    <!-- Font Awesome Icons -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <!-- Ionicons -->
    <link href="http://code.ionicframework.com/ionicons/2.0.0/css/ionicons.min.css" rel="stylesheet" type="text/css" />
    <!-- Morris chart -->
    <link href="~/Scripts/AdminLTE/plugins/morris/morris.css" rel="stylesheet" type="text/css" />
    <!-- jvectormap -->
    <link href="~/Scripts/AdminLTE/plugins/jvectormap/jquery-jvectormap-1.2.2.css" rel="stylesheet" type="text/css" />
    <!-- Daterange picker -->
    <link href="~/Scripts/AdminLTE/plugins/daterangepicker/daterangepicker-bs3.css" rel="stylesheet" type="text/css" />
    <!-- Theme style -->
    <link href="~/Content/AdminLTE/AdminLTE.min.css" rel="stylesheet" type="text/css" />
    @*TODO: AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load.*@
    <link href="~/Content/AdminLTE/skins/_all-skins.min.css" rel="stylesheet" type="text/css" />
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
    @Scripts.Render("~/bundles/modernizr")
</head>
<body class="skin-blue">

    <div class="wrapper">

        @Html.Partial("_AdminLteTopMenu")
        <!-- Left side column. contains the logo and sidebar -->
        @Html.Partial("_AdminLteLeftMenu")
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <section class="content-header">
                <h1>
                    @ViewBag.Title
                    <small>@ViewBag.TitleSmall</small>
                </h1>
                @Html.Partial("_AdminLteBreadcrumb")
            </section>
            <!-- Main content -->
            <section class="content">
                @RenderBody()
            </section><!-- /.content -->
        </div><!-- /.content-wrapper -->
        <footer class="main-footer">
            <div class="pull-right hidden-xs">
                <b>Version</b> 2.0
            </div>
            <strong>Copyright &copy; @DateTime.Now.Year <a href="http://almsaeedstudio.com">Almsaeed Studio</a>.</strong> All rights reserved.
        </footer>
    </div><!-- ./wrapper -->
    @* Bundles assume jquery 2.1.3 and Bootstrap 3 *@
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <!-- FastClick -->
    <script src='~/Scripts/AdminLTE/plugins/fastclick/fastclick.min.js'></script>
    <!-- AdminLTE App -->
    <script src="~/Scripts/AdminLTE/app.js" type="text/javascript"></script>
    <!-- Sparkline -->
    <script src="~/Scripts/AdminLTE/plugins/sparkline/jquery.sparkline.min.js" type="text/javascript"></script>
    <!-- jvectormap -->
    <script src="~/Scripts/AdminLTE/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js" type="text/javascript"></script>
    <script src="~/Scripts/AdminLTE/plugins/jvectormap/jquery-jvectormap-world-mill-en.js" type="text/javascript"></script>
    <!-- daterangepicker -->
    <script src="~/Scripts/AdminLTE/plugins/daterangepicker/daterangepicker.js" type="text/javascript"></script>
    <!-- datepicker -->
    <script src="~/Scripts/AdminLTE/plugins/datepicker/bootstrap-datepicker.js" type="text/javascript"></script>
    <!-- iCheck -->
    <script src="~/Scripts/AdminLTE/plugins/iCheck/icheck.min.js" type="text/javascript"></script>
    <!-- SlimScroll 1.3.0 -->
    <script src="~/Scripts/AdminLTE/plugins/slimScroll/jquery.slimscroll.min.js" type="text/javascript"></script>
    <!-- ChartJS 1.0.1 -->
    <script src="~/Scripts/AdminLTE/plugins/chartjs/Chart.min.js" type="text/javascript"></script>

    @RenderSection("scripts", required: false)
</body>
</html>

CompetentumWebApp/Views/Shared/_AdminLteLeftMenu.cshtml
@* 
 This partial controls the left menu of the AdminLTE dashboard and is called automatically by _AdminLteLayout
    This is where you can add, modify, or remove navigation options in your app
    TODO: This preserves the links as-is for the demo, which lead to broken pages!
    It's up to you to make sure these links either get deleted or lead somewhere REAL!
*@


@{
    Layout = null;
}
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <!-- Sidebar user panel -->
        <div class="user-panel">
            <div class="pull-left image">
                <img src="/Content/AdminLTE/img/user2-160x160.jpg" class="img-circle" alt="User Image" />
            </div>
            <div class="pull-left info">
                <p>Alexander Pierce</p>
                <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
        </div>
        <!-- search form -->
        @*<form action="#" method="get" class="sidebar-form">
            <div class="input-group">
                <input type="text" name="q" class="form-control" placeholder="Search..." />
                <span class="input-group-btn">
                    <button type='submit' name='search' id='search-btn' class="btn btn-flat"><i class="fa fa-search"></i></button>
                </span>
            </div>
        </form>*@
        <!-- /.search form -->
        <!-- sidebar menu: : style can be found in sidebar.less -->
        <ul class="sidebar-menu">
            <li class="header">MAIN NAVIGATION</li>
            
            <li>
                <a href="@Url.Action("ResumeView", "AdminLte")">
                    <i class="fa fa-table"></i> <span>База Данных Резюме</span>
                </a>
            </li>

            <li>
                @*<a href="@Url.Action("Index", "AdminLte")">*@
                <a href="@Url.Action("Index", "AdminLte")">
                    <i class="fa fa-edit"></i> <span>База Данных Вакансий</span>
                </a> 
            </li>

            <li>
                @*@Html.ActionLink("Добавить резюме с HeadHunter", "HeadHunter")*@

                <a href="@Url.Action("ExportToExcel", "AdminLte")">
                    <i class="fa fa-folder"></i> <span>Экспортировать вакансии</span>
                </a>
            </li>

            @*<li class="active treeview">
                <a href="#">
                    <i class="fa fa-dashboard"></i> <span>Dashboard</span> <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                    <li><a href="index.html"><i class="fa fa-circle-o"></i> Dashboard v1</a></li>
                    <li class="active"><a href="index2.html"><i class="fa fa-circle-o"></i> Dashboard v2</a></li>
                </ul>
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-files-o"></i>
                    <span>Layout Options</span>
                    <span class="label label-primary pull-right">4</span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="pages/layout/top-nav.html"><i class="fa fa-circle-o"></i> Top Navigation</a></li>
                    <li><a href="pages/layout/boxed.html"><i class="fa fa-circle-o"></i> Boxed</a></li>
                    <li><a href="pages/layout/fixed.html"><i class="fa fa-circle-o"></i> Fixed</a></li>
                    <li><a href="pages/layout/collapsed-sidebar.html"><i class="fa fa-circle-o"></i> Collapsed Sidebar</a></li>
                </ul>
            </li>
            <li>
                <a href="pages/widgets.html">
                    <i class="fa fa-th"></i> <span>Widgets</span> <small class="label pull-right bg-green">new</small>
                </a>
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-pie-chart"></i>
                    <span>Charts</span>
                    <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                    <li><a href="pages/charts/morris.html"><i class="fa fa-circle-o"></i> Morris</a></li>
                    <li><a href="pages/charts/flot.html"><i class="fa fa-circle-o"></i> Flot</a></li>
                    <li><a href="pages/charts/inline.html"><i class="fa fa-circle-o"></i> Inline charts</a></li>
                </ul>
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-laptop"></i>
                    <span>UI Elements</span>
                    <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                    <li><a href="pages/UI/general.html"><i class="fa fa-circle-o"></i> General</a></li>
                    <li><a href="pages/UI/icons.html"><i class="fa fa-circle-o"></i> Icons</a></li>
                    <li><a href="pages/UI/buttons.html"><i class="fa fa-circle-o"></i> Buttons</a></li>
                    <li><a href="pages/UI/sliders.html"><i class="fa fa-circle-o"></i> Sliders</a></li>
                    <li><a href="pages/UI/timeline.html"><i class="fa fa-circle-o"></i> Timeline</a></li>
                    <li><a href="pages/UI/modals.html"><i class="fa fa-circle-o"></i> Modals</a></li>
                </ul>
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-edit"></i> <span>Forms</span>
                    <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                    <li><a href="pages/forms/general.html"><i class="fa fa-circle-o"></i> General Elements</a></li>
                    <li><a href="pages/forms/advanced.html"><i class="fa fa-circle-o"></i> Advanced Elements</a></li>
                    <li><a href="pages/forms/editors.html"><i class="fa fa-circle-o"></i> Editors</a></li>
                </ul>
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-table"></i> <span>Tables</span>
                    <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                    <li><a href="pages/tables/simple.html"><i class="fa fa-circle-o"></i> Simple tables</a></li>
                    <li><a href="pages/tables/data.html"><i class="fa fa-circle-o"></i> Data tables</a></li>
                </ul>
            </li>
            <li>
                <a href="pages/calendar.html">
                    <i class="fa fa-calendar"></i> <span>Calendar</span>
                    <small class="label pull-right bg-red">3</small>
                </a>
            </li>
            <li>
                <a href="pages/mailbox/mailbox.html">
                    <i class="fa fa-envelope"></i> <span>Mailbox</span>
                    <small class="label pull-right bg-yellow">12</small>
                </a>
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-folder"></i> <span>Examples</span>
                    <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                    <li><a href="pages/examples/invoice.html"><i class="fa fa-circle-o"></i> Invoice</a></li>
                    <li><a href="pages/examples/login.html"><i class="fa fa-circle-o"></i> Login</a></li>
                    <li><a href="pages/examples/register.html"><i class="fa fa-circle-o"></i> Register</a></li>
                    <li><a href="pages/examples/lockscreen.html"><i class="fa fa-circle-o"></i> Lockscreen</a></li>
                    <li><a href="pages/examples/404.html"><i class="fa fa-circle-o"></i> 404 Error</a></li>
                    <li><a href="pages/examples/500.html"><i class="fa fa-circle-o"></i> 500 Error</a></li>
                    <li><a href="pages/examples/blank.html"><i class="fa fa-circle-o"></i> Blank Page</a></li>
                </ul>
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-share"></i> <span>Multilevel</span>
                    <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                    <li><a href="#"><i class="fa fa-circle-o"></i> Level One</a></li>
                    <li>
                        <a href="#"><i class="fa fa-circle-o"></i> Level One <i class="fa fa-angle-left pull-right"></i></a>
                        <ul class="treeview-menu">
                            <li><a href="#"><i class="fa fa-circle-o"></i> Level Two</a></li>
                            <li>
                                <a href="#"><i class="fa fa-circle-o"></i> Level Two <i class="fa fa-angle-left pull-right"></i></a>
                                <ul class="treeview-menu">
                                    <li><a href="#"><i class="fa fa-circle-o"></i> Level Three</a></li>
                                    <li><a href="#"><i class="fa fa-circle-o"></i> Level Three</a></li>
                                </ul>
                            </li>
                        </ul>
                    </li>
                    <li><a href="#"><i class="fa fa-circle-o"></i> Level One</a></li>
                </ul>
            </li>
            <li><a href="documentation/index.html"><i class="fa fa-book"></i> Documentation</a></li>*@
            <li class="header">LABELS</li>
            @*<li><a href="#"><i class="fa fa-circle-o text-danger"></i> Important</a></li>
            <li><a href="#"><i class="fa fa-circle-o text-warning"></i> Warning</a></li>
            <li><a href="#"><i class="fa fa-circle-o text-info"></i> Information</a></li>*@
        </ul>
    </section>
    <!-- /.sidebar -->
</aside>

CompetentumWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title – приложение ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Имя приложения", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Домашняя страница", "Index", "Home")</li>
                    <li>@Html.ActionLink("О программе", "About", "Home")</li>
                    <li>@Html.ActionLink("Контакт", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year – приложение ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>